### ISSUE TITLE
MP3 taking too long

### ISSUE THREAD

**Issue by next2non** [Algram/ytdl-webserver#1]
Hi

I ran the docker file and works as mentioned, but I have a request if possible. Currently when you paste a link inside the search bar I have to wait for the whole file to download so I can get the "download" button to click on. That is fine for short videos, but when I put videos of say 46min or so the process takes long till I get the download button. For one I don't know how long it has processed and how much is balanced (no idicatore) which could be frustrating especially if your running it from your mobile. 

Thus, my request, is it possible rather than downloading in the background, we get the "download URL link" which we can copy and use another app to download the file?

Regards,
Tariq

**Comment by Algram** [comment]
Another option would be to add a progress bar and a checkbox "Automatically Download" that starts the download in the browser right when youtube-dl finishes.

That would cover your usecase in my opinion.

**Comment by next2non** [comment]
Yeah that would do as well :)

**Comment by Algram** [comment]
@cedricium Sure, that would be awesome :100:
