### ISSUE TITLE
FFmpeg exited with code 1 as no temp folder was created by default.

### ISSUE THREAD

**Issue by ArunVenkata** [Algram/ytdl-webserver#10]
I downloaded the repo and after running the app, whenever I paste any link and click on the button the link appears in the list and it keeps loading.

I then learnt that the error was that there wasn't any temp folder created. After I created the folder myself, it ran smoothly. Is this a problem?

Debug: internal, implementation, error 
    Error: Uncaught error: ffmpeg exited with code 1: /home/arunvv53999/myimages/ytdl-webserver-master/public/temp/Train - Hey, Soul Sister.mp3: No such file or directory

**Comment by Algram** [comment]
Closed by #23.
