### ISSUE TITLE
Add host mount example to README

### ISSUE THREAD

**Issue by ahnick** [Algram/ytdl-webserver#2]
I think most people will want the youtube videos to reside on their host machine if they are running it from a laptop or single box.  This will allow them to be able to access the videos on their local filesystem, once they have been downloaded.  

I would suggest showing the preferred way of running the container as a host mount.  Something like the following...

`docker run -v /tmp/videos:/home/app/tmp/public -p 3000:3000 -d <your username>/ytdl-webserver`

Pathing on the host could be adjusted as desired.

**Comment by Algram** [comment]
That sounds like a very nice addition, feel free to open a PR for this and I will merge it :+1:

**Comment by Algram** [comment]
Closed by #3
