### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Algram** [Algram/ytdl-webserver#8]
As a developer I would like to update the outdated dependencies in this project, in order to fix security vulnerabilities and have an up-to-date project.

**Acceptance criteria**
- Dependencies are updated to a reasonably recent version
- Application still works (I think there might be some breaking changes when updating)

**Comment by mintunitish** [comment]
I want to do this.

**Comment by Algram** [comment]
@mintunitish Awesome, feel free to open a pull request!

**Comment by thangl3** [comment]
I have a pull request with your issue, you can check [https://github.com/Algram/ytdl-webserver/pull/25](here). Thanks.

**Comment by Algram** [comment]
Fixed by https://github.com/Algram/ytdl-webserver/commit/7dd8a049b930f7f21bb8064495fc65e4222f558a and https://github.com/Algram/ytdl-webserver/commit/036a1ee935233080f6843f222f7d35ec03be86d8
