### ISSUE TITLE
Q: Can I configure options e.g. download the Video and not audio-only?

### ISSUE THREAD

**Issue by tisba** [Algram/ytdl-webserver#9]
I'm running the server via the provided docker image like this:

```terminal
$ docker run -v /tmp:/home/app/public/temp --rm -p 3000:3000 algram/ytdl-webserver

> ytdl-webserver@1.0.1 start /home/app
> node ./src/server/server.js

Server running at: http://3c44bc0e995e:3000
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.

`info.filename` is deprecated, use `info._filename`
```

Dropping in URLs, I only get `.mp3` files in `/tmp`. Is there any way to configure this? Or is `ytdl-webserver` meant to be used as a "Youtube Video to MP3" tool, which is totally fine too of corse :)

**Comment by iwater** [comment]
@tisba https://github.com/Algram/ytdl-webserver/blob/master/src/server/server.js#L40

**Comment by tisba** [comment]
Ah okay, thanks @iwater.

In this case, should I let this issue open as a feature request? I could also open a new dedicated issue if that is preferred… /cc @Algram

**Comment by Algram** [comment]
@tisba A dedicated issue would be very nice. I will close this one after you open the new one!
